databaseConnection:
  database: quditlab
  echo: false
  host: localhost
  password: ''
  port: 5432
  user: python
hardware:
  DG4000 AWG:
    null:
      Visa Address: ''
      enabled: false
  Frequency Synthesizer PLLs:
    null:
      enabled: true
  Opal Kelly FPGA:
    null:
      bitFile: ./FPGA_Ions/IonControl-firmware-no-div.bit
      device: Pulser
      enabled: false
      uploadOnStartup: true
  VISA:
    null:
      enabled: false
showGui: false
software:
  Pulser:
    null:
      enabled: false
      hardware: Opal Kelly FPGA
useCustomDatabaseName: false
version: 2.0
